### ISSUE TITLE
Missing ini entries

### ISSUE THREAD

**Issue by Xarlith** [assetto-corsa-web/acweb#52]
Can missing ini entries be added in next version?

Option to enter custom AUTH_PLUGIN_ADDRESS in [SERVER] section is missing.
Same goes with lack of BALLAST and RESTRICTOR entries for entrylist generation/importing.
This is quite crucial since without AUTH_PLUGIN_ADDRESS anybody can enter server and with being unable to set ballst a big portion of server_cfg and entrylist has to be placed in custom field of the acweb editor.

**Comment by KoumaMisna** [comment]
And also if you want to use custom entry list you still have to add atleast one car via the web gui. If you don't you will get a message "At least one car must be added."

**Comment by Kugelschieber** [comment]
Oh sorry I forgot about this ticket for some time. I'm gonna try to fix it within the next one or two weeks :)

**Comment by Kugelschieber** [comment]
I've added all three of the fields and fixed the error message mentioned by @KoumaMisna
