### ISSUE TITLE
Cant save configuration

### ISSUE THREAD

**Issue by RellicX** [assetto-corsa-web/acweb#56]
Hey, 

i cant save the configuration in the webpanel. Connection between the plugin and mysql is working. I imported the shema.sql -> mig_1.0.3_1.1.0.sql -> mig_1.1.0_1.2.0.sql -> mig_1.2.1_1.3.0.sql -> mig_1.4.0_1.4.1.sql. SSH says "Error reading all configurations" and "Error saving configuration". 

These are the log errors: 

level=error msg="Error reading all configurations" err="missing destination name auth_plugin_address in *[]model.Configuration"
level=error msg="Error saving configuration" err="Error 1364: Field 'auth_plugin_address' doesn't have a default value"

**Comment by Kugelschieber** [comment]
It looks like you have installed 1.4.0 from the downloads page, but run the migration script for 1.4.1, which is not released yet. So reinitialize your database without the last script or remove the changes manually.

**Comment by RellicX** [comment]
Ahh, yeah. My Bad sorry! Its working now, thank you for your fast support! 👍 

When im trying to start an instance now, im getting this: 
level=debug msg="Adding new instance" instance="{9114 1 4 0xc420518160 0xc4201cd018}"
time="2018-12-11T13:04:54+01:00" level=error msg="Error when instance stopped" err="exit status 1" process_state="exit status 1"
time="2018-12-11T13:04:54+01:00" level=info msg="Instance removed" instance=0 pid=9114

Can you help me out there aswell?

**Comment by Kugelschieber** [comment]
9114 is the process ID and exit status 1 tells you that it exited with some kind of error. Make sure you can run Assetto Corsa without the web interface and all paths are correct. Maybe you're missing the server configuration. You can set those on the "Settings" page: https://github.com/assetto-corsa-web/acweb/blob/master/screenshots/screen4.png

**Comment by RellicX** [comment]
I did. My executable file is in the server folder and everything seems to be correct. 
Here is the log output from the interface: 

Server CFG Path :  configs/4/server_cfg.ini
Entry List Path :  configs/4/entry_list.ini
Assetto Corsa Dedicated Server v1.15
Protocol version: 202
Using cfg path:  configs/4/server_cfg.ini
configs/4/server_cfg.ini  NOT FOUND. EXITING

I checked that directory (/configs/4/). There are 2 files; server_cfg.ini and entry_list.ini. Both are readable and writeble for the www-data user.

**Comment by Kugelschieber** [comment]
Shouldn't the cfg path point to the directory instead of the file? I haven't bumped into this issue by myself.

**Comment by RellicX** [comment]
I dont know. The script point to that directory by itself. I set the using environment variables only to /configs.

**Comment by Kugelschieber** [comment]
Can you try running acweb with debugging enabled? That might give us more information. You can set the log level by changing the environment variable ACWEB_LOGLEVEL. On Linux for example: `export ACWEB_LOGLEVEL=debug` and then start your server.

**Comment by RellicX** [comment]
Okay. I did it but i think i got the same information. Here the log:

time="2018-12-11T15:58:55+01:00" level=info msg="Connecting to 'mysql' database 'acweb' at 'tcp(localhost:3306)'"
time="2018-12-11T15:58:55+01:00" level=info msg="Starting server on 0.0.0.0:8888"
time="2018-12-11T15:59:08+01:00" level=debug msg="Adding new instance" instance="{10373 1 4 0xc4202fc000 0xc4200a41e0}"
time="2018-12-11T15:59:08+01:00" level=error msg="Error when instance stopped" err="exit status 1" process_state="exit status 1"
time="2018-12-11T15:59:08+01:00" level=info msg="Instance removed" instance=0 pid=10373

Thanks for your help! Is there any way to contact you via Discord, Teamspeak or something?

**Comment by Kugelschieber** [comment]
Not today, probably at the weekend. You can contact me on Discord. Search for Kugel #5158.

**Comment by RellicX** [comment]
Cant find you. Can you try to catch me? RellicX #1628

Thanks alot!

**Comment by RellicX** [comment]
Its working now. 
I changed the directory from export ACWEB_CONFIG_DIR=configs
                                     to     export ACWEB_CONFIG_DIR=/var/www/html/configs

Thanks for your support and this great plugin :-) @Kugelschieber
