### ISSUE TITLE
typo config folder name

### ISSUE THREAD

**Issue by nicholascw** [assetto-corsa-web/acweb#60]
first is that I found my cars and tracks empty even though I configured the acServer directory correct.
then I found there's a "config" folder inside acweb root folder, and there are cars.json and tracks.json.
however after reading the log it said err reading car/track file, it's trying to read from "config**s**" folder and after I mv it to configs it seems working when adding configurations.

so here I am still wondering if it is standalone with the game folder, so every time I wish to add mod track/car I have to manually update the car/track files here?

Also I didn't get it work to import a server_cfg/entry_list , is it still in progress just with frontend ready?

**Comment by Kugelschieber** [comment]
Have you executed all migration scripts within the schema directory?

**Comment by nicholascw** [comment]
oh… are they required even if it's newly installed? (I thought they are for updates... I'll try exec those. thanks!

**Comment by Kugelschieber** [comment]
The config directory is read from the env variable ACWEB_CONFIG_DIR, I updated the documentation since it pointed to the wrong directory.
