### ISSUE TITLE
Can't login to the interface

### ISSUE THREAD

**Issue by Krydo1337** [assetto-corsa-web/acweb#63]
Hiho, i got an issue with the webinterface.
i've done the setup on windows server 2012 step by step. i installed mysql and for controlling the database i installed phpmyadmin.
i imported the ".sql" files with workbench than i seted the environment variables and started the .exe file.

the problem is, when i klick the login button after i write username "root" and password "root" the interface website doesn't do anything.

i hope anyone can help me :) sorry for my bad english.

**Comment by Kugelschieber** [comment]
Can you send me the log output by the server and from your browser (F12 -> Console -> try to login)?

**Comment by Krydo1337** [comment]
Ich denke mal du bist deutsch oder ? Zumindest mal laut deinem Namen
Das ist für mich ein wenig besser verständlich ^^

![prob](https://user-images.githubusercontent.com/47383411/52347647-c55d6e00-2a22-11e9-9314-94be47e8b44d.JPG)

Also das gibt die Console aus.
Habe node.js auch schon auf meinem Rootserver am laufen, aber da spuckt er den gleichen Fehler aus.

Danke für die schnelle Antwort :)

**Comment by Kugelschieber** [comment]
Liegt der Ordner public direkt neben der exe? Der kann die build.js im Ordner public/dist nicht finden. Ich habs gerade noch mal gecheckt, die liegt in der zip.

**Comment by Krydo1337** [comment]
Ja der Ordner liegt neben der .exe ich hab grad nochmal gecheckt. Ich habe die Ordnerstruktur genau so gelassen wie sie in der ".zip" war

hab mal ein paar snapshots gemacht

![prob1](https://user-images.githubusercontent.com/47383411/52360392-2fced800-2a3c-11e9-8640-ae76cfd3890f.JPG)
![prob2jpg](https://user-images.githubusercontent.com/47383411/52360398-32313200-2a3c-11e9-8982-585e7a8c79b7.JPG)
![prob3](https://user-images.githubusercontent.com/47383411/52360402-34938c00-2a3c-11e9-99a2-0d685386d1f0.JPG)

**Comment by Kugelschieber** [comment]
Muss ich prüfen, kann bissl dauern. Bisher habe ich nur Linux selbst getestet, falls das eine Option für dich ist. Über Docker oder so.

**Comment by Krydo1337** [comment]
hm es liegt vermutlich an Microsoft IIS ... der bekommt das mit dem JavaScript nicht gebacken ... ich werde gleich mal nen Apache Web Server einrichten und das da mal probieren. Wenn ich das Problem gefunden habe sage ich dir bescheid.

**Comment by Krydo1337** [comment]
Also auf Apache Webserver habe ich das gleiche Problem.

ich hab irgendwie das starke Gefühl dass es auch an den "environment variables" liegen könnte habe statt "set" "setx" nehmen müssen sonst wären sie nicht aufgenommen worden. 

durch "setx" sind sie halt nur als Benutzervariablen und nicht als Systemvariablen aufgenommen worden.

wenn du Lust hast können wir ja auch mal in Discord darüber schreiben. Habe irgendwie das gefühl ich bin der einzige mit dem Problem ^^

würde es sogar eventuell in betracht ziehen dir das ganze mal in einer Teamviewer-Sitzung zu demonstrieren falls es nicht anders möglich ist.

Falls das für dich überhaupt in Ordnung geht.

Discord: Krydo#2561

**Comment by Kugelschieber** [comment]
Ich werde das selbst mal unter Windows testen. Eigentlich ließt der Server die Dateien selbst relativ zum Ausführungsort aus. Da hat die Konfiguration nichts mit zu tun.

**Comment by Krydo1337** [comment]
Hab das ganze nun mal über den Internet Explorer ausgeführt. Da kommt ein Syntax-Fehler und der Cursor springt in den Bereich der in den Screenshots gelb markiert ist.

![prob](https://user-images.githubusercontent.com/47383411/52498953-8bcf6300-2bda-11e9-9296-5555a22d103e.JPG)

![prob1](https://user-images.githubusercontent.com/47383411/52498964-92f67100-2bda-11e9-90e2-cdb11d1a37de.JPG)

**Comment by Kugelschieber** [comment]
Ja der Internet Explorer mag kein ES6 :) Das war also zu erwarten.

**Comment by Krydo1337** [comment]
ja gut, ist ja auch kein wunder, ist ja auch der voldemort unter den explorern ...
ich bin schon wieder seit 2 stunden am testen wie ich das ganze zum laufen bekommen könnte,
langsam bin ich echt am limit angelangt mit meinen ideen :O

**Comment by Kugelschieber** [comment]
Ja lass erstmal, ich bekomme das wahrscheinlich schneller raus wenn ich es morgen oder später noch teste.

**Comment by Krydo1337** [comment]
okay .. danke dir schon mal.
Du hattest ja noch Docker als Lösung vorgeschlagen.
Das Läuft nur leider nicht unter Windows Server 2012 R2.
Bin schon auf der suche nach einer kompatiblen Version um das eben auch mal zu Testen.
Allerdings bin ich da auch noch nicht auf einen Nenner gekommen.

Sag bescheid wenn du den Fehler gefunden hast :)

**Comment by Kugelschieber** [comment]
Also bei mir startet es wie erwartet. Ich habe manuell alle Umgebungsvariablen via `set ACWEB_...=` gesetzt und dann acweb.exe gestartet. Das muss irgendwie mit deiner Ausführung zusammenhängen. Wichtig ist, dass acweb aus dem Installationsordner ausgeführt wird, weil die Webdateien relativ zum Ausführungsort gesucht werden. Liegt acwebe.exe z.B. unter C:\whatever\acweb\acweb.exe muss die exe aus dem Ordner C:\whatever\acweb\ gestartet werden.

**Comment by Krydo1337** [comment]
Hm... Dann muss bei mir wohl was mit den variablen net stimmen... Wurden die variablen bei dir als systemvariablen oder uservariablen eingetragen?.... Also "set ACWEB...." funkst bei mir z. B. Garnicht ich muss "setx..." machen. Sonst tut sich da garnix. 

Ich schicke dir einfach ma meine variablen:

setx ACWEB_HOST=(Adresse des Servers):8080
setx ACWEB_LOGDIR=
setx ACWEB_LOGLEVEL=info
setx ACWEB_INSTANCE_LOGDIR=instance_logs
setx ACWEB_CONFIG_DIR=config
setx ACWEB_TLS_PRIVATE_KEY=
setx ACWEB_TLS_CERT=
setx ACWEB_DB_TYPE=mysql
setx ACWEB_DB_USER=acweb (erstellter user) 
setx ACWEB_DB_PASSWORD=(passwort von db user)
setx ACWEB_DB_HOST=localhost:3306
setx ACWEB_DB=acweb (der datenbank name)

**Comment by Krydo1337** [comment]
Und muss unter den variablen nicht noch ein pfad angegeben werden dass der weiß wo der ordner der webseite überhaupt liegt oder kann der das automatisch zuordnen?

**Comment by Kugelschieber** [comment]
Der sucht relativ zum Ordner in dem du acweb startest. Wenn du einen Pfad angibst um acweb.exe zu starten, stimmt der Pfad nicht. Die Einstellungen sehen soweit gut aus, evt. brauchst du tcp(localhost:3306), aber wenns so geht ist auch okay.
Ich habe das direkt im normalen Windows Terminal ausprobiert. Vielleicht versuchst du das auch einmal lokal.

**Comment by Krydo1337** [comment]
Okay ich versuchs später nochmal. Bin z.Z. noch auf arbeit. Das einzige was mir grad auffällt was ich noch nicht erwähnt habe ist, dass die exe immer nur kurz aufgeht und sich direkt wieder schließt... Ich vermute mal wenn alles funkst muss die auf bleiben oder?

**Comment by Kugelschieber** [comment]
Ja richtig, der Server muss natürlich an bleiben. Wenn er es nicht bleibt, solltest du einen Fehler in im Terminal sehen, bzw. im Log. Versuch mal tcp() um deine MySQL Konfiguration zu setzen.

**Comment by Krydo1337** [comment]
Werde ich dann mal machen, ich halte dich auf dem laufenden
