### ISSUE TITLE
Integration for stracker and minorating

### ISSUE THREAD

**Issue by Kugelschieber** [assetto-corsa-web/acweb#7]
Integrate stracker and minorating.

**Comment by DeKugelschieber** [comment]
Cool, for stracker and minorating they use the stock server_cfg.ini/entry_list.ini files just with the following setup for use

UDP_PLUGIN_LOCAL_PORT=11000
UDP_PLUGIN_ADDRESS=127.0.0.1:50042
AUTH_PLUGIN_ADDRESS=localhost:9599/?ALLOWED=ABCN?

**Comment by theouteredge** [comment]
Hi, 

I was just looking at setting up the stracker plugin on a practice server, the plugin instructions say that I need to to point at the server_cfg.ini location.

how do you reference this from outside the docker container?

**Comment by Kugelschieber** [comment]
I'm not sure, so you might want to ask that on the forums. But I think you can expose the configuration directory (configured using ACWEB_CONFIG_DIR or look at its default) and point to that.

**Comment by Kugelschieber** [comment]
This should be solved with the new feature to execute scripts before/after server start.
